### PR TITLE
Compute standardized mean differences ref #78

### PR DESCRIPTION
**Pull request by tompollard**
This change adds an `smd` argument to compute pairwise standardized mean differences for continuous and categorical variables. Comparisons with the R package are shown below.

### R

```R
library(tidyverse)
library(tableone)

path = "https://raw.githubusercontent.com/tompollard/tableone/master/data/pn2012_demo.csv"

pn = read.csv(path)

cols = c("Age","SysABP","Height","Weight","ICU","MechVent","LOS","death")
strata = "MechVent"
tabUnmatched <- CreateTableOne(vars = cols, strata = strata, data = pn, test = FALSE)

print(tabUnmatched, smd = TRUE)
```

Screen Shot 2020-04-30 at 00 52 08

### Python

```py

path = "https://raw.githubusercontent.com/tompollard/tableone/master/data/pn2012_demo.csv"

df = pd.read_csv(path)

cols = ["Age", "SysABP", "Height", "Weight", "ICU", "MechVent", "LOS", "death"]
categorical=["ICU", "MechVent", "death"]
strata = "MechVent"

t = TableOne(df, categorical=categorical, label_suffix=True, groupby=strata, 
    pval=True, pval_test_name=False, smd=True)

```

Screen Shot 2020-04-30 at 00 51 48

### R

```R
library(tableone)

path = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/rhc.csv"
df = read.csv(path)

vars <- c("age","sex","race","edu","income","ninsclas","cat1","das2d3pc",
          "dnr1","ca","surv2md1","aps1","scoma1","wtkilo1","temp1","meanbp1",
          "resp1","hrt1","pafi1","paco21","ph1","wblc1","hema1","sod1","pot1",
          "crea1","bili1","alb1","resp","card","neuro","gastr","renal",
          "meta","hema","seps","trauma","ortho","cardiohx","chfhx",
          "dementhx","psychhx","chrpulhx","renalhx","liverhx","gibledhx",
          "malighx","immunhx", "transhx","amihx")

tabUnmatched <- CreateTableOne(vars = vars, strata = "swang1", data = rhc, test = FALSE)

print(tabUnmatched, smd = TRUE)
```

Screen Shot 2020-04-30 at 01 02 40

### Python

```Python

path = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/rhc.csv"
df = pd.read_csv(path)

path = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/rhc.csv"
df = pd.read_csv(path)

cols = ["age","sex","race","edu","income","ninsclas","cat1","das2d3pc","dnr1",
          "ca","surv2md1","aps1","scoma1","wtkilo1","temp1","meanbp1","resp1",
          "hrt1","pafi1","paco21","ph1","wblc1","hema1","sod1","pot1","crea1",
          "bili1","alb1","resp","card","neuro","gastr","renal","meta","hema",
          "seps","trauma","ortho","cardiohx","chfhx","dementhx","psychhx",
          "chrpulhx","renalhx","liverhx","gibledhx","malighx","immunhx",
          "transhx","amihx"]

cats = ["race", "income", "ninsclas", "cat1", "dnr1", "ca", "resp",
        "card", "neuro", "gastr", "renal", "meta", "hema", "seps", "trauma",
        "ortho", "sex"]

t = TableOne(df, columns=cols, categorical=cats, label_suffix=True, groupby="swang1", 
             pval=False, pval_test_name=False, smd=True)
t
```

Screen Shot 2020-04-30 at 01 03 15

### CODE REVIEW

**Comment by jraffa** [comment]
Looks good.  I'll take a closer look later.  Any thoughts on the +/- compared to `R`?

**Comment by tompollard** [comment]
> Any thoughts on the +/- compared to R?

Good point, I wasn't sure how best to handle this so it would be interesting to hear your thoughts. It feels like the sign offers some useful information, so I prefer not to remove it unless it is confusing. 

I've given the name of the two groups in the column header (unlike R) which makes the sign more meaningful, but it may not be clear to the user that the left group is the control and the right is the treatment (i.e. `SMD (0,1)` means that 0 is the control and 1 is the treatment).

**Comment by tompollard** [comment]
While I think of it, I wasn't clear whether Hedges correction was valid for the categorical SMD. It doesn't really matter because the option for applying the correction isn't offered, but it would be good to know.

**Comment by raheems** [comment]
Thanks for the updates. Is it available yet in PyPI?

**Comment by tompollard** [comment]
@raheems not yet, but it should be shortly (after a little more testing, and hopefully feedback from @jraffa)

**Comment by raheems** [comment]
I was able to use the `smd` feature. Thanks!!

**Pull request merged**
